Repository galaxybomb23/Decision-Tree-Plus-Plus, pull requests merged in 2024-12, with the labels that each got.

#39 19 classify with decision tree
  include/DecisionTree.hpp
  include/Utility.hpp
  src/DecisionTree.cpp
  src/Utility.cpp
  test/ClassifyTest.cpp
  test/ConstructTreeTest.cpp
  test/Sandbox.py
Labels: enhancement

#43 6 decision tree introspection
  CMakeLists.txt
  UserManual.md
  include/Common.hpp
  include/DTIntrospection.hpp
  include/DecisionTree.hpp
  include/Utility.hpp
  run
  src/DTIntrospection.cpp
  src/DecisionTree.cpp
  src/EvalTrainingData.cpp
  test/IntrospectionTest.cpp
  test/Sandbox.cpp
  test/Sandbox.py
Labels: documentation, enhancement

#42 add documentation for src code
  include/DecisionTree.hpp
  include/DecisionTreeNode.hpp
  include/EvalTrainingData.hpp
  include/TrainingDataGeneratorNumeric.hpp
  include/TrainingDataGeneratorSymbolic.hpp
  src/DecisionTree.cpp
  src/DecisionTreeNode.cpp
  src/EvalTrainingData.cpp
  src/TrainingDataGeneratorNumeric.cpp
  src/TrainingDataGeneratorSymbolic.cpp
  src/Utility.cpp
Labels: documentation

#44 38 interactive classification with decision tree
  CMakeLists.txt
  include/DecisionTree.hpp
  src/DecisionTree.cpp
  test/Sandbox.cpp
  test/Sandbox.py
Labels: enhancement
